### ISSUE TITLE
bio gold in not train mode

### ISSUE THREAD

**Issue by antgr** [WindChimeRan/pytorch_multi_head_selection_re#10]
https://github.com/WindChimeRan/pytorch_multi_head_selection_re/blob/30c8aa1b2d89a115612d2c5f344e96ab132220c8/lib/models/selection.py#L191
Hi is this the bio_gold? Or is it inferred?

**Comment by WindChimeRan** [comment]
The training and inference are different.

bio_gold is used for bio embedding latter. 

Training: use gold BIO

Testing: use inferred BIO
