### ISSUE TITLE
what should I do if the sentence is longer more？Do you have any suggests，please？

### ISSUE THREAD

**Issue by moyan007** [WindChimeRan/pytorch_multi_head_selection_re#16]
Thanks for your sharing firstly! And I am working on the Joint entity recognition and relation extraction over a long text which the average length is about 1000 tokens. Could you please give me some advices for that? I have tried to adjust the length of config json file, but the performance is very pool. Like this:
Triplets-> p: 0.0000, r: 0.0000, f: 0.0000 ||NER->p: 1.0000, r: 0.0000, f: 0.0000

**Comment by WindChimeRan** [comment]
No, you should not use MHS for long sentences, because the space complexity is O(relation x length x length). You can try my new method: [Seq2UMTree](https://github.com/WindChimeRan/OpenJERE).
