### ISSUE TITLE
run experiment

### ISSUE THREAD

**Issue by antgr** [WindChimeRan/pytorch_multi_head_selection_re#2]
Hi, thank you for this great effort.
You say that it can be run using the commands:
(1),(2),(3)
python main.py --mode preprocessing --exp_name chinese_selection_re
python main.py --mode train --exp_name chinese_selection_re 
python main.py --mode evaluation --exp_name chinese_selection_re

I am a bit confused. How should I reproduce the official run (CoNLL04 i think)?  
(Are the above commands (1,2,3) for 2019 Language and Intelligence Challenge ?)

**Comment by WindChimeRan** [comment]
Hi, I update my README!

Yes, chinese_selection_re is for the competition.

If you want to try CoNLL04, please set **exp_name** as **conll_selection_re**

eg:

python main.py --mode preprocessing --exp_name conll_selection_re
python main.py --mode train --exp_name conll_selection_re
python main.py --mode evaluation --exp_name conll_selection_re

The hyperparameters are different from the official version, but I don't want to exactly reproduce the paper.

I am adding BERT to the model.
