### ISSUE TITLE
No such file or directory error

### ISSUE THREAD

**Issue by antgr** [WindChimeRan/pytorch_multi_head_selection_re#3]
FileNotFoundError: [Errno 2] No such file or directory: 'data/conll/multi_head_selection/word_vocab.json'

command: python main.py --mode train --exp_name conll_selection_re

**Comment by WindChimeRan** [comment]
As I said in README, you have to

1. preprocessing
2. train
3. evaluation

preprocessing will generate all the vocab needed.
