### ISSUE TITLE
Bert model, and '11'

### ISSUE THREAD

**Issue by antgr** [WindChimeRan/pytorch_multi_head_selection_re#9]
In this line you search for the string 11. What does that mean, could you clarify?
Thank you!
https://github.com/WindChimeRan/pytorch_multi_head_selection_re/blob/30c8aa1b2d89a115612d2c5f344e96ab132220c8/lib/models/selection.py#L60

**Comment by antgr** [comment]
OK, means ``` # only update last layer ```
Could you consider create a function like that:
```
def isBertsLastLayer:
   return '11' in name
```

**Comment by WindChimeRan** [comment]
Sorry for my ugly code. PR welcomes.

**Comment by antgr** [comment]
No, your code is very good. I will make a PR, if you want that change.
